// src/ui/input/VisitStrip.svelte
<script lang="ts">
	// src/ui/input/VisitStrip.svelte
	// Three 48px dart slots showing the active player's current-visit darts.
	// Tapping a slot dispatches UNDO (removes last dart; tapping earlier slot undoes back to it).
	// On bust, strip background animates to destructive red.
	import { matchStore } from '../../stores/match.svelte.js';
	import type { DartScore } from '../../engine/types.js';

	function formatDart(dart: DartScore): string {
		if (dart.segment === 0) return '0 (Daneben)';
		if (dart.multiplier === 2 && dart.segment === 25) return 'Bull';        // inner bull: { multiplier: 2, segment: 25 }
		if (dart.multiplier === 1 && dart.segment === 25) return 'Outer Bull';  // outer bull: { multiplier: 1, segment: 25 }
		const prefix = dart.multiplier === 3 ? 'T' : dart.multiplier === 2 ? 'D' : '';
		return `${prefix}${dart.segment}`;
	}

	// Slots: always show 3 slots
	const SLOTS = [0, 1, 2];

	// Detect bust: check if last visit of active player was a bust
	// We show bust styling when the current visit has ended and was a bust,
	// but during the correction window the last completed visit is in the player's visits array.
	// For the current visit strip, we check if a bust is pending confirmation.
	function isBustVisit(): boolean {
		const player = matchStore.activePlayer;
		if (!player) return false;
		const visits = player.visits;
		if (visits.length === 0) return false;
		return visits[visits.length - 1].bust;
	}
</script>

<div class="visit-strip" class:bust={isBustVisit()}>
	{#each SLOTS as slotIdx (slotIdx)}
		{@const dart = matchStore.currentVisit[slotIdx]}
		<button
			class="dart-slot"
			onclick={() => matchStore.dispatch({ type: 'UNDO' })}
			aria-label={dart ? `Rückgängig: ${formatDart(dart)}` : 'Leerer Dart-Slot'}
			disabled={matchStore.currentVisit.length === 0}
		>
			{dart ? formatDart(dart) : '—'}
		</button>
	{/each}
</div>

<style>
	.visit-strip {
		display: flex;
		flex-direction: row;
		gap: var(--space-xs);
		align-items: center;
		padding: var(--space-xs) var(--space-md);
		transition: background-color var(--dur-slow) var(--ease);
	}

	.visit-strip.bust {
		background-color: var(--destructive-line);
	}

	.dart-slot {
		height: 48px;
		flex: 1;
		min-width: 80px;
		background: var(--surface);
		border: 1px solid var(--line-strong);
		border-radius: var(--radius-sm);
		color: var(--text);
		font-size: 14px;
		font-weight: 400;
		cursor: pointer;
		display: flex;
		align-items: center;
		justify-content: center;
		transition: background-color var(--dur-base) var(--ease);
	}

	.dart-slot:disabled {
		opacity: 0.5;
		cursor: default;
	}

	.dart-slot:not(:disabled):active {
		background: var(--surface-3);
		transform: scale(var(--press-scale));
	}
</style>

// design/components/scoring/VisitStrip.jsx
import React from 'react';
import { formatDart } from './DartPill.jsx';

function slotLabel(dart) {
  if (!dart) return '—';
  if (dart.segment === 0) return '0 (Daneben)';
  if (dart.multiplier === 2 && dart.segment === 25) return 'Bull';
  if (dart.multiplier === 1 && dart.segment === 25) return 'Outer Bull';
  return formatDart(dart);
}

/** Three 56px dart slots for the current visit. Tapping a filled slot = UNDO. Bust tints the strip red. */
export function VisitStrip({ darts = [], bust = false, onUndo }) {
  return (
    <div style={{
      display: 'flex', gap: 'var(--space-sm)', alignItems: 'center',
      padding: 'var(--space-xs) var(--space-md)', borderRadius: 'var(--radius-md)',
      transition: 'background-color var(--dur-slow) var(--ease)',
      backgroundColor: bust ? 'var(--destructive-soft)' : 'transparent',
      boxShadow: bust ? 'inset 0 0 0 1px var(--destructive-line)' : 'none',
    }}>
      {[0, 1, 2].map((i) => {
        const filled = !!darts[i];
        return (
          <button key={i} disabled={darts.length === 0} onClick={onUndo} style={{
            height: 'var(--control-h)', flex: 1, minWidth: 80,
            background: filled ? 'var(--surface-2)' : 'var(--surface)',
            border: filled ? '1px solid var(--line-strong)' : '1px dashed var(--line-strong)',
            borderRadius: 'var(--radius-sm)',
            color: filled ? 'var(--text)' : 'var(--text-faint)',
            fontSize: 'var(--text-md)', fontWeight: filled ? 600 : 400,
            cursor: darts.length === 0 ? 'default' : 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontFamily: 'var(--font-ui)', fontVariantNumeric: 'tabular-nums',
            boxShadow: filled ? 'var(--edge-highlight)' : 'none',
            transition: 'background var(--dur-base) var(--ease), border-color var(--dur-base) var(--ease)',
            WebkitTapHighlightColor: 'transparent',
          }}>{slotLabel(darts[i])}</button>
        );
      })}
    </div>
  );
}
